# Changes here will be overwritten by Copier
_commit: cb07c66
_src_path: git@github.com:zinchenkomig/front-template.git
custom_container_registry: cr.yandex
domain: mikhailzinchenko.test
email: ''
image_name: cr.yandex/crp6fqsjle6nrluiklb6/common/frontend
is_custom_container_registry: true
project_name: front_template
tg_bot_id: anything
